services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
